-- ─── MIGRATION: UPDATE SUBSCRIPTION TIERS ────────────────────────────

-- 1. Remove the old check constraint
-- We need to find the name of the constraint first.
-- Usually it's users_plan_check or similar if generated by Postgres.
-- To be safe, we'll try to drop and recreate it.

ALTER TABLE public.users 
DROP CONSTRAINT IF EXISTS users_plan_check;

-- 2. Add the new expanded check constraint
ALTER TABLE public.users 
ADD CONSTRAINT users_plan_check 
CHECK (plan IN ('free', 'starter', 'growth', 'pro', 'enterprise'));

-- 3. (Optional) Set default plan if needed
ALTER TABLE public.users 
ALTER COLUMN plan SET DEFAULT 'free';

-- ──────────────────────────────────────────────────────────────────
